stages:
    data_ingestion:
      cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      deps:
        - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
        - config/config.yaml
      outs:
        - artifacts/data_ingestion/kidney-ct-scan-image

    prepare_base_model:
      cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      deps:
        - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
        - config/config.yaml
      params:
        - IMAGE_SIZE
        - INCLUDE_TOP
        - CLASSES
        - WEIGHTS
      outs:
        - artifacts/prepare_base_model

    training:
      cmd: python src/cnnClassifier/pipeline/stage_03_model_training.py
      deps:
        - src/cnnClassifier/pipeline/stage_03_model_training.py
        - artifacts/data_ingestion/kidney-ct-scan-image
        - artifacts/prepare_base_model
        - config/config.yaml
      params:
        - IMAGE_SIZE
        - BATCH_SIZE
        - EPOCHS
        - AUGMENTATION
      outs:
        - artifacts/training/model.h5

    evaluation:
      cmd: python src/cnnClassifier/pipeline/stage_04_model_evalution.py
      deps:
        - src/cnnClassifier/pipeline/stage_04_model_evalution.py
        - artifacts/training/model.h5
        - artifacts/data_ingestion/kidney-ct-scan-image
        - config/config.yaml
      params:
        - IMAGE_SIZE
        - BATCH_SIZE
      metrics:
        - scores.json:
            cache: false